deploymentMode: SingleBinary

loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
    type: filesystem
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumes:
    - name: loki-data
      emptyDir: {}
  extraVolumeMounts:
    - name: loki-data
      mountPath: /var/loki

gateway:
  enabled: false

minio:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  dashboards:
    enabled: false
  serviceMonitor:
    enabled: false
  rules:
    enabled: false
