alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: devops-demo

grafana:
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      url: http://loki.loki.svc.cluster.local:3100
      access: proxy
      isDefault: false

    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo.tempo.svc.cluster.local:3200
      access: proxy
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: "-2s"
          spanEndTimeShift: "2s"
          filterByTraceID: true
          filterBySpanID: false
