apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: devops-demo-api
spec:
  replicas: 2

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: devops-demo-api

  strategy:
    canary:
      stableService: devops-demo-api-stable
      canaryService: devops-demo-api-canary

      trafficRouting:
        nginx:
          stableIngress: devops-demo-api-ingress

      maxSurge: 1
      maxUnavailable: 0

      steps:
        - setWeight: 10
        - analysis:
            templates:
              - templateName: devops-demo-api-success-rate
        - pause:
            duration: 30s
        - setWeight: 50
        - analysis:
            templates:
              - templateName: devops-demo-api-success-rate
        - pause:
            duration: 30s
        - setWeight: 100

  template:
    metadata:
      labels:
        app: devops-demo-api
      annotations:
        rollout-demo: "analysis-test-1"

    spec:
      terminationGracePeriodSeconds: 30

      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: devops-demo-api
          image: ghcr.io/harshuk1702/devops-demo-api:930effe4a85b9f33c64d09da55d7c41b2ac78ac7

          ports:
            - containerPort: 8000

          env:
            - name: OTEL_SERVICE_NAME
              value: "devops-demo-api"

            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://tempo.tempo.svc.cluster.local:4318/v1/traces"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3