tempo:
  reportingEnabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

persistence:
  enabled: false

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
